# Generated by Django 3.2.4 on 2021-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=50)),
                ('pages', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
